### ISSUE TITLE
how to get result from sandbox?

### ISSUE THREAD

**Issue by kostya** [jessedoyle/duktape.cr#26]
``` crystal
key = Duktape::Sandbox.new.eval!("eval(#{key});").as(String)
```

this is return Int32

**Comment by kostya** [comment]
i guess just create runtime and function?

**Comment by jessedoyle** [comment]
Yea that's one of the main reasons that I created the `Runtime` class. 

The developer can also call the low-level api methods on the `Sandbox` or `Context` instance if they require fine-grained control.

The relevant methods to grab values from the Duktape stack are here: [get functions](https://github.com/jessedoyle/duktape.cr/blob/master/src/duktape/api/get.cr) (only raise on invalid stack index) or [require functions](https://github.com/jessedoyle/duktape.cr/blob/master/src/duktape/api/require.cr) (raises on type differences).

i.e.

``` crystal
sbx = Duktape::Sandbox.new
sbx.eval!("1;")
sbx.get_number(-1) # => 1.0 (interpret the last stack value as a number and return it)
```
