### ISSUE TITLE
Disable coloring output

### ISSUE THREAD

**Issue by vladfaust** [jessedoyle/duktape.cr#48]
`print` called within Duktape puts the output colored in blue. Sometimes color codes aren't rendered properly (in my example -- in Sublime Text build output). What I see is:

```
[96mYou are 29 years old.[0m
```

I wonder if this coloring a part of this very binding or Duktape itself or even javascript (:laughing:)? BTW, `console.log` outputs in white but still with color codes:

```
[97mYou are 29 years old.[0m
```

And if it's the part of this binding, I guess it should be at least allowed to configured, or even removed.

_P.S: Thanks for the shard, it otherwise works smoothly! :heart:_

**Comment by jessedoyle** [comment]
`duktape.cr` definitlely makes use of Crystal's `colorize` method when rendering output - it's not coming directly from the engine (see: https://github.com/jessedoyle/duktape.cr/search?q=colorize&unscoped_q=colorize). 

I think adding a flag to disable colored and styled terminal output would be great!

Would a flag in an environment variable work for your use-case? (i.e. `DUKTAPE_COLORED_OUTPUT=false`)?

It may take me a few weeks to look into implementing such a flag - I'd absolutely be open to any pull requests with an implementation!

I do think that keeping the default colored output is ideal (i.e. one must opt-out of colored output, but it is enabled by default).

**Comment by jessedoyle** [comment]
Thinking a bit more on the subject, there may be a flag present already upstream in Crystal that disables the `colorize` functionality for non-TTY based apps. 

See: https://github.com/crystal-lang/crystal/blob/5282fdf913cdf8a1bdf84afc148b238e91a4889e/src/colorize.cr#L128-L130.

I'm curious, does the following configuration disable colored output in your app?

```crystal
require "colorize"
Colorize.on_tty_only!
```

EDIT: As per the `colorize` documentation here: https://github.com/crystal-lang/crystal/blob/5282fdf913cdf8a1bdf84afc148b238e91a4889e/src/colorize.cr#L111-L124, it's possible to disable colored output permanently as such:

```crystal
require "colorize"
Colorize.enabled = false
```

**Comment by vladfaust** [comment]
Great, disabling `Colorize` works as expected.

I'm wondering why

> I do think that keeping the default colored output is ideal

Just interested. It's your project etc. etc. but for me, I always try to follow SOLID principles and coloring output of an embedded language falls out of its responsibility IMO.

**Comment by jessedoyle** [comment]
@vladfaust 
> Just interested. It's your project etc. etc. but for me, I always try to follow SOLID principles and coloring output of an embedded language falls out of its responsibility IMO.

That's a fair observation. In my opinion it's all for developer experience.

I believe that the majority of Crystal users are interacting with their programs via an ANSI-color enabled terminal. The fact that Crystal includes the `colorize` method in its standard library and that it is [widely](https://github.com/luckyframework/lucky/search?q=colorize&unscoped_q=colorize) [used](https://github.com/crystal-lang/shards/search?q=colorize&unscoped_q=colorize) in many popular CLI-based tools supports this notion.

I believe that colorizing output enhances the developer experience and makes software tools easier to work with. Could you imagine how unwelcoming the [Rails development server](https://github.com/rails/rails/blob/1b402a510aeac38b40c0bc6c9b9dfb1cc61c71cb/activesupport/lib/active_support/log_subscriber.rb#L124-L133) would be if it didn't colorize its output by default?

Finally, `Duktape.cr` uses color to draw the developer's attention to a few things:

* The differences between [`alert`](https://github.com/jessedoyle/duktape.cr/blob/165ee9bd3c0cbe728982133e136faa1deb1e4b12/src/duktape/builtin/alert.cr#L19) and [`print`](https://github.com/jessedoyle/duktape.cr/blob/165ee9bd3c0cbe728982133e136faa1deb1e4b12/src/duktape/builtin/print.cr#L19) messages. Alert messages are printed to standard error in yellow, print messages are printed to standard out in light cyan.
* Various [log levels](https://github.com/jessedoyle/duktape.cr/blob/165ee9bd3c0cbe728982133e136faa1deb1e4b12/src/duktape/logger.cr#L40-L54) in the Duktape.cr logger are colorized to assist the the developer when debugging.

As long as there's always a way to disable colorized output, I think we're in a good spot.

**Comment by jessedoyle** [comment]
As we've established a good mechanism to disable colorized output [here](https://github.com/jessedoyle/duktape.cr/issues/48#issuecomment-480956687), I'm going to close this issue.

I would accept a PR to add documentation about disabling colorized output if anyone is interested.
